### ISSUE TITLE
freetype needed as dependency, already installed

### ISSUE THREAD

**Issue by jrherr** [biobakery/homebrew-biobakery#9]
I've been banging my head against this error for a while:

```
==> Installing lefse from biobakery/biobakery
==> Downloading https://bitbucket.org/nsegata/lefse/get/e3cabe93a0d1.tar.gz
Already downloaded: /Users/trane/Library/Caches/Homebrew/lefse-1.0.0-dev-e3cabe9.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
Already downloaded: /Users/trane/Library/Caches/Homebrew/lefse--numpy-1.11.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec --single-
==> Downloading https://pypi.python.org/packages/source/m/matplotlib/matplotlib-1.5.1.tar.gz
Already downloaded: /Users/trane/Library/Caches/Homebrew/lefse--matplotlib-1.5.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec --single-
Last 15 lines from /Users/trane/Library/Logs/Homebrew/lefse/02.python:
                 cairo: no  [cairocffi or pycairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues

➜  brew install freetype
Warning: freetype 2.8 is already installed
```

My anaconda, LaTeX, and other dependencies seem to be working fine.

**Comment by ljmciver** [comment]
Hello - I am sorry you have been having issues with matplotlib/freetype. I have found matplotlib needs to find a specific header file in a particular location to work and brew/package managers don't always install it in this location. If you run "$ locate freetype | grep ft2build.h" it will tell you where brew placed the file. Then symlink it to where matplotlib is expecting it "$ sudo ln -s /usr/include/freetype2/ft2build.h /usr/include/". This should resolve the error you are seeing. Please reopen this issue if you continue to see errors. I will also add this to the readme incase other users have this issue too.

Alternatively, if you continue to have issues with dependencies and would like to use Docker instead (and have elevated permissions on the machine to run Docker or a container engine is available) we have Docker images for all bioBakery tools. [https://hub.docker.com/u/biobakery/](https://hub.docker.com/u/biobakery/)

Please feel free to open issues when you have problems! Don't want you to get to the head banging point!

Thanks,
Lauren

**Comment by jrherr** [comment]
Hi Lauren, 
Thanks so much for your message! I truly appreciate it and you were very helpful!

I'm still getting the same error. First I can check for ft2build.h:
```
$ locate freetype | grep ft2build.h                                                                 
/Users/trane/anaconda2/include/freetype2/ft2build.h
/Users/trane/anaconda2/pkgs/freetype-2.5.5-2/include/freetype2/ft2build.h
/Users/trane/anaconda3/include/freetype2/ft2build.h
/Users/trane/anaconda3/pkgs/freetype-2.5.5-2/include/freetype2/ft2build.h
/usr/local/Cellar/freetype/2.7.1/include/freetype2/ft2build.h
/usr/local/Cellar/freetype/2.8/include/freetype2/ft2build.h
```

I've tried to symlink all the the above and none of them work. I'm still getting the same error:

```
python2 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/strainphlan/2.6.0/libexec/vendor --singl
Last 15 lines from /Users/trane/Library/Logs/Homebrew/strainphlan/24.python2:
                 cairo: no  [cairocffi or pycairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: yes [version 9.21]
                 latex: no
               pdftops: no

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

==============================================================
                        * The following required packages can not be built:
                        * freetype

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues
```

Any other ideas?

Thanks again for your helpfulness and your messages! I truly appreciate your help!

**Comment by ljmciver** [comment]
Hello - Sorry that did not fix your error. I would pick one of the brew installs to symlink:
$ ln -s /usr/local/Cellar/freetype/2.8/include/freetype2/ft2build.h /usr/include/

You might also have to install pkg-config with "$ brew install pkg-config". Hopefully the two of these together will resolve your error. Also are you using brew and conda together? I see odd behavior when trying to use both at the same time. For example, installing brew packages in a conda environment the paths are not expected. From what I have seen I don't think they are compatible. 

Thanks,
Lauren

**Comment by amusheg** [comment]
Hello! I am having this exact same problem trying to brew install lefse. Unfortunately, the symlink solution suggested here gives an "Operation not permitted" error; this seems to be related to System Integrity Protection on OSX, which I would rather not disable. Is there another workaround?

**Comment by ljmciver** [comment]
Hello - Sorry that is the only work around I know for the freetype install location expected for matplotlib. We also host docker images for all biobakery tools if that is something you would like to try.

Thanks!
Lauren
